[package]
name = "argui-dsl-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Incremental Argui DSL compiler and Rust AOT backend"

[dependencies]
argui-dsl-ir = { path = "../dsl-ir" }
argui-dsl-semantic = { path = "../dsl-semantic" }
argui-schema.workspace = true
argui-shader.workspace = true

[lints]
workspace = true
