[package]
name = "argui-web-demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
argui = { path = "../argui" }
argui-devtools.workspace = true
argui-effects = { workspace = true, features = ["artistic"] }
argui-showcase.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true
