import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '../../..')
const contract = JSON.parse(readFileSync(resolve(root, 'packages/host/src/contract.generated.json'), 'utf8'))
const valueType = {
  Bool: 'boolean', Int: 'number', Float: 'number', String: 'string', Name: 'string',
  Color: 'string', Brush: 'string', Dimension: 'number | string',
  Insets: 'number | readonly number[]', Radii: 'number | readonly number[]',
  Border: 'object', Shadow: 'object', Transform: 'object', Asset: 'AssetRef',
}
const lines = [
  '// Generated by packages/react/scripts/generate-jsx.mjs from argui-schema.',
  "import type { ReactNode, Ref } from 'react'",
  "import type { AssetRef } from '@argui/host'",
  "import type { WorkNode } from './tree'",
  'export namespace JSX {',
  '  export type Element = import(\'react\').ReactElement',
  "  export interface IntrinsicAttributes { key?: import('react').Key }",
  '  export interface ElementChildrenAttribute { children: {} }',
  '  export interface IntrinsicElements {',
]
for (const native of contract.natives) {
  const tag = native.name[0].toLowerCase() + native.name.slice(1)
  lines.push(`    ${tag}: {`)
  for (const property of native.properties) {
    if (!property.readOnly) {
      const name = property.name === 'key' ? 'nativeKey' : property.name
      lines.push(`      ${name}${property.required ? ':' : '?:'} ${valueType[property.valueType] ?? 'unknown'}`)
    }
  }
  for (const event of native.events) {
    const name = 'on' + event.name.replace(/(^|_)([a-z])/g, (_, _separator, letter) => letter.toUpperCase())
    lines.push(`      ${name}?: (payload: unknown) => void`)
  }
  lines.push("      key?: import('react').Key")
  lines.push('      ref?: Ref<WorkNode>')
  lines.push('      children?: ReactNode')
  lines.push('    }')
}
lines.push('  }', '}', '')
writeFileSync(resolve(root, 'packages/react/src/jsx.generated.ts'), lines.join('\n'))
