[package]
name = "argui-showcase"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
argui-animation.workspace = true
argui-core.workspace = true
argui-image.workspace = true
argui-paint.workspace = true
argui-runtime.workspace = true
argui-text.workspace = true
argui-theme.workspace = true
argui-ui.workspace = true

[dev-dependencies]
argui-layout.workspace = true

[lints]
workspace = true
