[package]
name = "argui-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
argui-paint.workspace = true
argui-text.workspace = true
bytemuck.workspace = true
wgpu.workspace = true

[dev-dependencies]
argui-core.workspace = true

[lints]
workspace = true
