//! Closed public string domains for built-in native properties.

use crate::PropertyId;

use super::*;

/// Returns accepted values for a built-in string property.
///
/// `id` is a canonical built-in property ID. An empty slice means the
/// property is not a closed string domain.
pub(super) fn allowed_values(id: PropertyId) -> &'static [&'static str] {
    match id {
        DIRECTION_SCOPE => &["ltr", "rtl"],
        SCROLLBAR_SIDE => &["left", "right"],
        ALIGN_ITEMS | ALIGN_SELF | JUSTIFY_ITEMS | JUSTIFY_SELF => {
            &["start", "center", "end", "stretch"]
        }
        JUSTIFY_CONTENT => &[
            "start",
            "center",
            "end",
            "spaceBetween",
            "spaceAround",
            "spaceEvenly",
        ],
        ALIGN_CONTENT => &[
            "start",
            "center",
            "end",
            "stretch",
            "spaceBetween",
            "spaceAround",
            "spaceEvenly",
        ],
        GRID_AUTO_FLOW => &["row", "column", "rowDense", "columnDense"],
        POSITION => &["relative", "absolute", "sticky"],
        FIT => &["fill", "contain", "cover"],
        SAMPLING => &["linear", "nearest"],
        TEXT_FONT_STYLE => &["normal", "italic", "oblique"],
        TEXT_UNDERLINE => &["none", "single", "double"],
        TEXT_ALIGN => &["start", "end", "left", "right", "center", "justify"],
        TEXT_OVERFLOW => &[
            "clip",
            "ellipsis",
            "ellipsisStart",
            "ellipsisMiddle",
            "ellipsisEnd",
        ],
        TEXT_PRIVACY => &["public", "password", "revealedPassword"],
        FOCUS_CONTAINMENT => &["none", "trap", "modal"],
        KEYBOARD_ACTIVATION => &["none", "enter", "enterOrSpace"],
        DISMISS_POLICY => &[
            "manual",
            "outsidePointer",
            "escape",
            "outsidePointerOrEscape",
            "outsideHoverOrEscape",
        ],
        WINDOW_LAYER => &[
            "background",
            "content",
            "floating",
            "popover",
            "modal",
            "debug",
        ],
        PLACEMENT => &[
            "fill",
            "center",
            "topStart",
            "top",
            "topEnd",
            "bottomStart",
            "bottom",
            "bottomEnd",
            "leftStart",
            "left",
            "leftEnd",
            "rightStart",
            "right",
            "rightEnd",
        ],
        SEMANTIC_CHECKED_STATE => &["unchecked", "checked", "mixed"],
        SEMANTIC_CURRENT => &["true", "page", "step", "location", "date", "time"],
        SEMANTIC_LIVE => &["off", "polite", "assertive"],
        SEMANTIC_ORIENTATION => &["horizontal", "vertical"],
        SEMANTIC_HAS_POPUP => &["menu", "listBox", "tree", "grid", "dialog"],
        SEMANTIC_SORT => &["ascending", "descending"],
        SEMANTIC_ROLE => &[
            "generic",
            "window",
            "group",
            "navigation",
            "text",
            "heading",
            "image",
            "link",
            "button",
            "checkBox",
            "radioButton",
            "radioGroup",
            "switch",
            "textInput",
            "textArea",
            "searchInput",
            "table",
            "grid",
            "row",
            "columnHeader",
            "cell",
            "list",
            "listItem",
            "tree",
            "treeItem",
            "listBox",
            "option",
            "menu",
            "menuItem",
            "menuBar",
            "menuItemCheckBox",
            "menuItemRadio",
            "comboBox",
            "tooltip",
            "status",
            "alertDialog",
            "slider",
            "progress",
            "tab",
            "tabList",
            "tabPanel",
            "dialog",
            "alert",
            "separator",
        ],
        MOUSE_CURSOR => &[
            "auto",
            "default",
            "contextMenu",
            "help",
            "pointer",
            "progress",
            "wait",
            "cell",
            "crosshair",
            "text",
            "verticalText",
            "alias",
            "copy",
            "move",
            "noDrop",
            "notAllowed",
            "grab",
            "grabbing",
            "eResize",
            "nResize",
            "neResize",
            "nwResize",
            "sResize",
            "seResize",
            "swResize",
            "wResize",
            "ewResize",
            "nsResize",
            "neswResize",
            "nwseResize",
            "colResize",
            "rowResize",
            "allScroll",
            "zoomIn",
            "zoomOut",
            "dndAsk",
            "allResize",
        ],
        _ => &[],
    }
}
