//! Compile-time path construction shared by AOT and live asset loading.

use argui_core::{Point, Size};
use argui_dsl_semantic::vector_path::{self, PathCommandSpec};
use argui_paint::VectorId;
use argui_vector::{PathCommand, PathStyle, path_asset};

use super::*;

/// Lowers one static `path()` expression to a validated, embedded vector asset.
///
/// * `node` — complete checked path call.
/// * `source` — source and owner identity of the expression.
/// * `context` — asset table receiving the generated bytes and any error.
///
/// Returns an asset-ID expression consumed by both execution paths.
pub(super) fn lower(
    node: &SyntaxNode,
    source: SourceInfo,
    context: &mut Context<'_>,
) -> IrExpression {
    let spec = match vector_path::parse(node) {
        Ok(spec) => spec,
        Err(error) => return invalid(node, context, error.message),
    };
    let commands = spec
        .commands
        .into_iter()
        .map(|command| match command {
            PathCommandSpec::MoveTo(x, y) => PathCommand::MoveTo(Point::new(x, y)),
            PathCommandSpec::LineTo(x, y) => PathCommand::LineTo(Point::new(x, y)),
            PathCommandSpec::QuadraticTo(cx, cy, x, y) => PathCommand::QuadraticTo {
                control: Point::new(cx, cy),
                end: Point::new(x, y),
            },
            PathCommandSpec::CubicTo(c1x, c1y, c2x, c2y, x, y) => PathCommand::CubicTo {
                first_control: Point::new(c1x, c1y),
                second_control: Point::new(c2x, c2y),
                end: Point::new(x, y),
            },
            PathCommandSpec::Close => PathCommand::Close,
        })
        .collect::<Vec<_>>();
    let style = PathStyle {
        fill: spec.fill,
        stroke_width: (spec.stroke_width != 0.0).then_some(spec.stroke_width),
        even_odd: spec.even_odd,
    };
    let asset = match path_asset(
        VectorId(1),
        Size::new(spec.width, spec.height),
        &commands,
        style,
    ) {
        Ok(asset) => asset,
        Err(error) => return invalid(node, context, format!("invalid path geometry: {error}")),
    };
    let bytes = asset.svg.to_vec();
    let svg = std::str::from_utf8(&bytes).expect("path_asset generates UTF-8 SVG");
    let path = format!("__generated__/path/{:016x}.svg", hash_text(svg));
    let id = AssetId::from_raw(hash_text(&path));
    context
        .assets
        .entry(path.clone())
        .or_insert_with(|| crate::IrAsset {
            id,
            path,
            kind: crate::AssetKind::Vector,
            inline_bytes: Some(bytes),
        });
    IrExpression {
        id: expression_id(&source),
        value_type: IrType::Asset,
        kind: IrExpressionKind::Asset(id),
        source,
    }
}
