import { readdirSync, writeFileSync } from 'node:fs'
import { join, relative, resolve, sep } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const directory = join(root, 'assets')
const source = []

function visit(folder) {
  for (const entry of readdirSync(folder, { withFileTypes: true })) {
    const path = join(folder, entry.name)
    if (entry.isDirectory()) visit(path)
    else if (/\.(svg|png|jpe?g|webp)$/i.test(entry.name)) source.push(path)
  }
}
visit(directory)

const used = new Set()
const assets = source.map((path) => {
  const key = relative(directory, path).split(sep).join('/')
  if (!/^[A-Za-z0-9_./-]+$/.test(key)) throw new Error(`Unsupported asset path: ${key}`)
  const kind = key.toLowerCase().endsWith('.svg') ? 'svg' : 'image'
  let hash = 0xcbf29ce484222325n
  for (const byte of new TextEncoder().encode(`${kind}:${key}`)) {
    hash = ((hash ^ BigInt(byte)) * 0x100000001b3n) & 0xffffffffffffffffn
  }
  const id = Number(hash & 0x1fffffffffffffn)
  if (!id || used.has(id)) throw new Error(`Asset ID collision: ${key}`)
  used.add(id)
  return { key, kind, id }
}).sort((a, b) => a.key.localeCompare(b.key))

const manifest = { version: 1, assets }
writeFileSync(join(root, 'assets.generated.json'), JSON.stringify(manifest, null, 2) + '\n')
const types = [
  '// Generated by apps/gallery/scripts/generate-assets.mjs.',
  "import type { AssetRef } from '@argui/host'",
  'export const mediaAssets = {',
  ...assets.map(({ key, kind, id }) => `  ${JSON.stringify(key)}: { kind: '${kind}', id: ${id} },`),
  '} as const satisfies Record<string, AssetRef>',
  '',
]
writeFileSync(join(root, 'src/assets.generated.ts'), types.join('\n'))
const rust = [
  '// Generated by apps/gallery/scripts/generate-assets.mjs.',
  'pub(crate) const EMBEDDED: &[AssetInput<\'static>] = &[',
  ...assets.map(({ key, kind, id }) =>
    `    AssetInput { key: ${JSON.stringify(key)}, kind: AssetKind::${kind === 'svg' ? 'Svg' : 'Image'}, id: ${id}, bytes: include_bytes!("assets/${key}") },`),
  '];',
  '',
]
writeFileSync(join(root, 'assets.generated.rs'), rust.join('\n'))
