[package]
name = "argui-effects"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
blur = []
shadow = []
color = []
refraction = []
liquid-glass = []
artistic = []
scroll = ["dep:argui-ui"]

[dependencies]
argui-paint.workspace = true
argui-render.workspace = true
argui-ui = { workspace = true, optional = true }

[lints]
workspace = true

[dev-dependencies]
wgpu.workspace = true
pollster.workspace = true
