[package]
name = "argui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
tray = ["argui-platform/tray", "argui-runtime/tray"]

[dependencies]
argui-animation.workspace = true
argui-core.workspace = true
argui-devtools.workspace = true
argui-layout.workspace = true
argui-paint.workspace = true
argui-platform.workspace = true
argui-render.workspace = true
argui-runtime.workspace = true
argui-text.workspace = true
argui-ui.workspace = true
argui-vector.workspace = true

[dev-dependencies]
argui-effects = { workspace = true, features = ["artistic"] }
argui-showcase.workspace = true

[lints]
workspace = true
