mod binding;
mod expression;
mod node;
mod types;

use std::{collections::HashMap, fmt::Write};

use argui_dsl_ir::{ComponentId, FieldId, IrComponent, IrProject, TokenId};
use argui_dsl_semantic::{
    ComponentDefinition, Definition, DefinitionKind, SemanticProject, SymbolId,
};

use crate::{CompilerError, Reachability};

pub(super) struct Context<'a> {
    ir: &'a IrProject,
    reachable: &'a Reachability,
    schema: &'a argui_schema::SchemaRegistry,
    definitions: HashMap<SymbolId, &'a Definition>,
    components: HashMap<ComponentId, &'a IrComponent>,
    component_definitions: HashMap<ComponentId, &'a ComponentDefinition>,
    field_names: HashMap<FieldId, String>,
    token_functions: HashMap<TokenId, String>,
}

/// Emits direct typed Rust construction code for one reachable IR graph.
pub(super) fn emit(
    semantic: &SemanticProject,
    ir: &IrProject,
    reachable: &Reachability,
    entry: &str,
    public_api_hash: u64,
    schema: &argui_schema::SchemaRegistry,
) -> Result<String, CompilerError> {
    let context = Context::new(semantic, ir, reachable, schema);
    let mut output = String::new();
    writeln!(output, "// @generated by argui-dsl-compiler; do not edit.").unwrap();
    writeln!(output, "pub mod argui_generated {{").unwrap();
    writeln!(output, "#![allow(clippy::type_complexity)]").unwrap();
    // Parentheses emitted around arbitrary DSL expressions preserve precedence at every call site.
    writeln!(output, "#![allow(unused_parens)]").unwrap();
    writeln!(output, "#[allow(unused_imports)] use std::cell::RefCell;").unwrap();
    writeln!(output, "#[allow(unused_imports)] use std::rc::Rc;").unwrap();
    writeln!(output, "use std::sync::atomic::{{AtomicU64, Ordering}};").unwrap();
    writeln!(
        output,
        "pub const PUBLIC_API_HASH: u64 = {public_api_hash};"
    )
    .unwrap();
    writeln!(
        output,
        "static NEXT_INSTANCE: AtomicU64 = AtomicU64::new(1);"
    )
    .unwrap();
    writeln!(
        output,
        "type NativeEventCallback = Box<dyn Fn(&::argui::ui::UiEvent)>;"
    )
    .unwrap();
    writeln!(
        output,
        "type Translator = Rc<dyn Fn(&str) -> Option<String>>;"
    )
    .unwrap();
    writeln!(output, "type NativeEventRegistrar<'a> = Option<&'a mut dyn FnMut(NativeEventCallback) -> ::argui::ui::EventHandler>;").unwrap();
    writeln!(
        output,
        "fn next_instance() -> u64 {{ NEXT_INSTANCE.fetch_add(1, Ordering::Relaxed).max(1) }}"
    )
    .unwrap();
    writeln!(output, "/// Derives a stable nested owner from a component site's retained identity.\nfn child_owner(identity: &::argui::ui::RetainedIdentity) -> u64 {{ use ::std::hash::{{Hash, Hasher}}; let mut hash = ::std::collections::hash_map::DefaultHasher::new(); identity.hash(&mut hash); hash.finish().max(1) }}").unwrap();
    writeln!(output, "thread_local! {{ static NATIVE_REGISTRY: ::argui::schema::SchemaRegistry = ::argui::schema::builtin::registry().expect(\"generated native schema is valid\"); }}").unwrap();
    writeln!(output, "thread_local! {{ #[allow(dead_code)] static ACTIVE_THEME_MODE: ::std::cell::Cell<u64> = const {{ ::std::cell::Cell::new(0) }}; }}").unwrap();
    writeln!(output, "#[allow(dead_code)] fn theme_mode_id(name: &str) -> u64 {{ let mut hash = 0xcbf2_9ce4_8422_2325_u64; for byte in name.bytes() {{ hash ^= u64::from(byte); hash = hash.wrapping_mul(0x0000_0100_0000_01b3); }} hash }}").unwrap();
    let mode_ids = ir
        .themes
        .iter()
        .flat_map(|theme| &theme.modes)
        .map(|mode| format!("{}_u64", mode.id.raw()))
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect::<Vec<_>>()
        .join(" | ");
    let valid_mode = if mode_ids.is_empty() {
        "false".to_string()
    } else {
        format!("matches!(id, {mode_ids})")
    };
    writeln!(output, "#[allow(dead_code)] fn set_theme_mode(name: String) {{ let id = theme_mode_id(&name); if !{valid_mode} {{ eprintln!(\"unknown theme mode `{{name}}`\"); return; }} ACTIVE_THEME_MODE.with(|active| active.set(id)); }}").unwrap();
    writeln!(output, "fn construct_native(id: ::argui::schema::NativeTypeId, input: &::argui::schema::NativeElementInput) -> ::argui::ui::Element {{ NATIVE_REGISTRY.with(|registry| registry.construct(id, input).expect(\"AOT input was schema checked\")) }}").unwrap();
    context.emit_types(&mut output)?;
    context.emit_tokens(&mut output)?;
    context.emit_assets(&mut output)?;
    context.emit_effects(&mut output)?;
    for component in ir.components.iter().filter(|component| {
        reachable.components.contains(&component.id) && component.template_slots.is_empty()
    }) {
        context.emit_component_renderer(&mut output, component)?;
    }
    let entry_module = semantic
        .modules
        .iter()
        .find(|module| module.path == entry)
        .ok_or_else(|| CompilerError::MissingEntry(entry.into()))?;
    for definition in entry_module
        .definitions
        .iter()
        .filter(|definition| definition.exported)
    {
        if let DefinitionKind::Component(component) = &definition.kind {
            let id = ComponentId::from_raw(definition.id.raw());
            if reachable.components.contains(&id) {
                if !context.components[&id].template_slots.is_empty() {
                    return Err(CompilerError::Codegen(
                        "template components cannot be application roots".into(),
                    ));
                }
                context.emit_public_component(&mut output, definition, component, id)?;
            }
        }
    }
    writeln!(output, "}}").unwrap();
    writeln!(output, "pub use argui_generated::*;").unwrap();
    Ok(output)
}

impl<'a> Context<'a> {
    /// Builds codegen indices from resolved IDs to source ABI names.
    fn new(
        semantic: &'a SemanticProject,
        ir: &'a IrProject,
        reachable: &'a Reachability,
        schema: &'a argui_schema::SchemaRegistry,
    ) -> Self {
        let definitions = semantic
            .modules
            .iter()
            .flat_map(|module| &module.definitions)
            .map(|definition| (definition.id, definition))
            .collect::<HashMap<_, _>>();
        let components = ir
            .components
            .iter()
            .map(|component| (component.id, component))
            .collect::<HashMap<_, _>>();
        let mut component_definitions = HashMap::new();
        let mut field_names = HashMap::new();
        for value in &ir.structs {
            if let Some(Definition {
                kind: DefinitionKind::Struct(source),
                ..
            }) = definitions.get(&value.symbol)
            {
                for (field, lowered) in source.fields.iter().zip(&value.fields) {
                    field_names.insert(lowered.id, types::rust_identifier(&field.name));
                }
            }
        }
        for definition in definitions.values() {
            if let DefinitionKind::Component(component) = &definition.kind {
                let id = ComponentId::from_raw(definition.id.raw());
                component_definitions.insert(id, component);
            }
        }
        let token_functions = ir
            .themes
            .iter()
            .flat_map(|theme| &theme.tokens)
            .map(|token| (token.id, format!("theme_token_{}", token.id.raw())))
            .collect();
        Self {
            ir,
            reachable,
            schema,
            definitions,
            components,
            component_definitions,
            field_names,
            token_functions,
        }
    }

    /// Emits reachable user struct and enum Rust equivalents.
    fn emit_types(&self, output: &mut String) -> Result<(), CompilerError> {
        for definition in self.definitions.values() {
            match &definition.kind {
                DefinitionKind::Struct(value)
                    if self.reachable.structs.contains(&definition.id) =>
                {
                    writeln!(output, "#[derive(Clone, Debug, Default, PartialEq)]").unwrap();
                    writeln!(
                        output,
                        "pub struct {} {{",
                        types::type_name(&definition.name)
                    )
                    .unwrap();
                    for field in &value.fields {
                        writeln!(
                            output,
                            "pub {}: {},",
                            types::rust_identifier(&field.name),
                            self.rust_type(&field.value_type)?
                        )
                        .unwrap();
                    }
                    writeln!(output, "}}").unwrap();
                }
                DefinitionKind::Enum(value) if self.reachable.enums.contains(&definition.id) => {
                    let name = types::type_name(&definition.name);
                    writeln!(output, "#[derive(Clone, Debug, PartialEq)]").unwrap();
                    writeln!(output, "pub enum {name} {{").unwrap();
                    for (variant, _) in &value.variants {
                        writeln!(output, "{},", types::type_name(variant)).unwrap();
                    }
                    writeln!(output, "}}").unwrap();
                    if let Some((first, _)) = value.variants.first() {
                        writeln!(
                            output,
                            "impl Default for {name} {{ fn default() -> Self {{ Self::{} }} }}",
                            types::type_name(first)
                        )
                        .unwrap();
                    }
                }
                _ => {}
            }
        }
        Ok(())
    }

    /// Emits typed functions for reachable tokens and active-mode overrides.
    fn emit_tokens(&self, output: &mut String) -> Result<(), CompilerError> {
        let mut defaults = std::collections::BTreeMap::new();
        for theme in &self.ir.themes {
            if !self.reachable.themes.contains(&theme.id) {
                continue;
            }
            for token in &theme.tokens {
                if self.reachable.tokens.contains(&token.id) {
                    defaults.insert(token.id, token);
                }
            }
        }
        for (id, token) in defaults {
            let name = &self.token_functions[&id];
            let mut modes = std::collections::BTreeMap::new();
            for theme in &self.ir.themes {
                if !self.reachable.themes.contains(&theme.id) {
                    continue;
                }
                for mode in &theme.modes {
                    for (target, value) in &mode.overrides {
                        if *target == id {
                            modes.insert(mode.id, value);
                        }
                    }
                }
            }
            if modes.is_empty() {
                writeln!(
                    output,
                    "fn {name}() -> {} {{ {} }}",
                    self.ir_rust_type(&token.value_type)?,
                    self.expression(&token.default, &Default::default())?
                )
                .unwrap();
                continue;
            }
            writeln!(
                output,
                "fn {name}() -> {} {{ match ACTIVE_THEME_MODE.with(|mode| mode.get()) {{",
                self.ir_rust_type(&token.value_type)?
            )
            .unwrap();
            for (mode, value) in modes {
                writeln!(
                    output,
                    "{}_u64 => {},",
                    mode.raw(),
                    self.expression(value, &Default::default())?
                )
                .unwrap();
            }
            writeln!(
                output,
                "_ => {}, }} }}",
                self.expression(&token.default, &Default::default())?
            )
            .unwrap();
        }
        Ok(())
    }

    /// Emits compile-time embedded reachable assets.
    fn emit_assets(&self, output: &mut String) -> Result<(), CompilerError> {
        let media_assets = self
            .ir
            .assets
            .iter()
            .filter(|asset| {
                self.reachable.assets.contains(&asset.id)
                    && matches!(
                        asset.kind,
                        argui_dsl_ir::AssetKind::Image | argui_dsl_ir::AssetKind::Vector
                    )
            })
            .collect::<Vec<_>>();
        for asset in &self.ir.assets {
            if self.reachable.assets.contains(&asset.id) {
                if let Some(bytes) = crate::project::builtin_asset_bytes(&asset.path) {
                    let bytes = bytes
                        .iter()
                        .map(u8::to_string)
                        .collect::<Vec<_>>()
                        .join(",");
                    writeln!(
                        output,
                        "pub static ASSET_{}: &[u8] = &[{bytes}];",
                        asset.id.raw()
                    )
                    .unwrap();
                } else {
                    writeln!(output, "pub static ASSET_{}: &[u8] = include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\"));", asset.id.raw(), escape(&asset.path)).unwrap();
                }
            }
        }
        if media_assets.is_empty() {
            writeln!(output, "thread_local! {{ static MEDIA_ASSETS: ::argui::schema::AssetRegistry = ::argui::schema::AssetRegistry::new(); }}").unwrap();
            writeln!(output, "#[allow(dead_code)] fn asset_handle(id: u64) -> ::argui::schema::AssetHandle {{ panic!(\"unknown media asset {{id}}\") }}").unwrap();
        } else {
            writeln!(output, "thread_local! {{ static MEDIA_ASSETS: ::argui::schema::AssetRegistry = {{ let mut assets = ::argui::schema::AssetRegistry::new();").unwrap();
            for asset in &media_assets {
                let method = match asset.kind {
                    argui_dsl_ir::AssetKind::Image => "upsert_image",
                    argui_dsl_ir::AssetKind::Vector => "upsert_vector",
                    _ => unreachable!("media filter only includes images and vectors"),
                };
                writeln!(output, "assets.{method}(::argui::schema::AssetKey::new(\"{}\").expect(\"validated asset key\"), ASSET_{}).expect(\"validated embedded asset\");", escape(&asset.path), asset.id.raw()).unwrap();
            }
            writeln!(output, "assets }}; }}").unwrap();
            writeln!(output, "fn asset_handle(id: u64) -> ::argui::schema::AssetHandle {{ MEDIA_ASSETS.with(|assets| {{ let path = match id {{").unwrap();
            for asset in &media_assets {
                writeln!(output, "{} => \"{}\",", asset.id.raw(), escape(&asset.path)).unwrap();
            }
            writeln!(output, "_ => panic!(\"unknown media asset {{id}}\") }}; assets.get(&::argui::schema::AssetKey::new(path).expect(\"validated asset key\")).expect(\"registered embedded asset\").handle() }}) }}").unwrap();
        }
        writeln!(output, "pub fn image_assets() -> Vec<::argui::paint::ImageAsset> {{ MEDIA_ASSETS.with(|assets| assets.records().filter_map(|record| match record {{ ::argui::schema::AssetRecord::Image {{ asset, .. }} => Some(asset.clone()), _ => None }}).collect()) }}").unwrap();
        writeln!(output, "pub fn vector_assets() -> Vec<::argui::paint::VectorAsset> {{ MEDIA_ASSETS.with(|assets| assets.records().filter_map(|record| match record {{ ::argui::schema::AssetRecord::Vector {{ asset, .. }} => Some(asset.clone()), _ => None }}).collect()) }}").unwrap();
        Ok(())
    }

    /// Emits validated custom effect definitions for renderer registration.
    fn emit_effects(&self, output: &mut String) -> Result<(), CompilerError> {
        writeln!(
            output,
            "pub fn effect_definitions() -> Vec<::argui::render::EffectDefinition> {{ vec!["
        )
        .unwrap();
        for effect in &self.ir.effects {
            if !self.reachable.effects.contains(&effect.id) {
                continue;
            }
            let asset = self
                .ir
                .assets
                .iter()
                .find(|asset| asset.id == effect.shader)
                .ok_or_else(|| CompilerError::Codegen("effect shader asset is missing".into()))?;
            writeln!(output, "::argui::render::EffectDefinition::new(::argui::paint::EffectId::new(\"dsl.{}\"), [", effect.id.raw()).unwrap();
            let definition = self
                .definitions
                .values()
                .find(|definition| definition.id.raw() == effect.id.raw());
            if let Some(Definition {
                kind: DefinitionKind::Effect(source),
                ..
            }) = definition
            {
                for parameter in &source.parameters {
                    writeln!(
                        output,
                        "::argui::render::EffectParameter::new(\"{}\", {}),",
                        escape(&parameter.name),
                        types::effect_parameter_type(&parameter.value_type)?
                    )
                    .unwrap();
                }
            }
            writeln!(output, "], [::argui::render::EffectPassDefinition::fragment(\"main\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\"))) ]),", escape(&asset.path)).unwrap();
        }
        writeln!(output, "] }}").unwrap();
        Ok(())
    }

    /// Emits one internal renderer receiving typed reactive properties directly.
    fn emit_component_renderer(
        &self,
        output: &mut String,
        component: &IrComponent,
    ) -> Result<(), CompilerError> {
        let definition = self.component_definition(component.id)?;
        write!(
            output,
            "fn render_component_{}(owner: u64, translator: &Translator, property_motions: &mut ::argui::schema::PropertyMotionStore, child_properties: &mut ::argui::reactive::RetainedPropertyStore<::argui::ui::RetainedIdentity>, virtual_viewports: &::std::collections::HashMap<::argui::ui::RetainedIdentity, f32>, reduced_motion: bool",
            component.id.raw()
        )
        .unwrap();
        for (source, property) in definition.properties.iter().zip(&component.properties) {
            write!(
                output,
                ", p_{}: ::argui::reactive::Property<{}>, presented_p_{}: Option<{}>",
                property.id.raw(),
                self.rust_type(&source.value_type)?,
                property.id.raw(),
                self.rust_type(&source.value_type)?
            )
            .unwrap();
        }
        for (source, callback) in definition.callbacks.iter().zip(&component.callbacks) {
            write!(
                output,
                ", c_{}: {}",
                callback.id.raw(),
                self.callback_type(source)?
            )
            .unwrap();
        }
        for slot in &component.slots {
            write!(output, ", s_{}: Vec<::argui::ui::Element>", slot.raw()).unwrap();
        }
        writeln!(
            output,
            ", handlers: &mut NativeEventRegistrar<'_>) -> ::argui::ui::Element {{"
        )
        .unwrap();
        writeln!(output, "let _ = translator;").unwrap();
        writeln!(
            output,
            "let _ = &mut *property_motions; let _ = reduced_motion;"
        )
        .unwrap();
        writeln!(output, "let _ = &mut *child_properties;").unwrap();
        writeln!(output, "let _ = virtual_viewports;").unwrap();
        writeln!(output, "let _ = &mut *handlers;").unwrap();
        writeln!(output, "let mut roots = Vec::new();").unwrap();
        let mut scope = expression::Scope {
            translator: Some("translator".into()),
            ..expression::Scope::default()
        };
        for property in &component.properties {
            scope
                .properties
                .insert(property.id, format!("p_{}", property.id.raw()));
            let rendered = format!("_input_rendered_p_{}", property.id.raw());
            writeln!(
                output,
                "let {rendered} = presented_p_{}.unwrap_or_else(|| p_{}.get());",
                property.id.raw(),
                property.id.raw()
            )
            .unwrap();
            scope
                .rendered_properties
                .insert(property.id, format!("{rendered}.clone()"));
        }
        for callback in &component.callbacks {
            scope
                .callbacks
                .insert(callback.id, format!("c_{}", callback.id.raw()));
        }
        for slot in &component.slots {
            scope.slots.insert(*slot, format!("s_{}", slot.raw()));
        }
        for animation in &component.animations {
            if let Some(site) = animation.owner {
                scope
                    .animations
                    .insert((site, animation.property), animation.clone());
            }
        }
        for state in &component.states {
            if let Some(site) = state.owner {
                scope.states.entry(site).or_default().push(state.clone());
            } else {
                scope.component_states.push(state.clone());
            }
        }
        let mut rendered_properties = Vec::new();
        for property in &component.properties {
            let target = argui_dsl_ir::PropertyTargetId::Component(property.id);
            let selected = self.select_own_state_value(
                target,
                format!("p_{}.get()", property.id.raw()),
                &property.value_type,
                &scope,
            )?;
            let animation = component
                .animations
                .iter()
                .find(|animation| animation.owner.is_none() && animation.property == target);
            if animation.is_none() && selected.active.is_none() {
                continue;
            }
            let variable = format!("rendered_p_{}", property.id.raw());
            let sampled = if let Some(animation) = animation {
                let identity = format!(
                    "::argui::ui::RetainedIdentity::new(owner, {})",
                    component.id.raw()
                );
                self.animated_decl_expression(animation, target, &selected, &scope, &identity)?
            } else {
                selected.effective
            };
            writeln!(output, "let {variable} = {sampled};").unwrap();
            rendered_properties.push((property.id, variable));
        }
        scope.rendered_properties.extend(rendered_properties);
        self.emit_nodes(output, &component.body, "roots", 0, &scope, None)?;
        writeln!(output, "if roots.len() == 1 {{ roots.remove(0) }} else {{ ::argui::ui::Element::container(roots) }}").unwrap();
        writeln!(output, "}}").unwrap();
        Ok(())
    }

    /// Emits the Rust-facing strongly typed wrapper for an exported root.
    fn emit_public_component(
        &self,
        output: &mut String,
        definition: &Definition,
        source: &ComponentDefinition,
        id: ComponentId,
    ) -> Result<(), CompilerError> {
        let ir = self.components[&id];
        let name = types::type_name(&definition.name);
        writeln!(
            output,
            "pub struct {name} {{ instance: u64, translator: RefCell<Translator>, property_motions: RefCell<::argui::schema::PropertyMotionStore>, child_properties: RefCell<::argui::reactive::RetainedPropertyStore<::argui::ui::RetainedIdentity>>, virtual_viewports: RefCell<::std::collections::HashMap<::argui::ui::RetainedIdentity, f32>> ,"
        )
        .unwrap();
        for property in &source.properties {
            writeln!(
                output,
                "{}: ::argui::reactive::Property<{}>,",
                types::rust_identifier(&property.name),
                self.rust_type(&property.value_type)?
            )
            .unwrap();
        }
        for (callback, lowered) in source.callbacks.iter().zip(&ir.callbacks) {
            writeln!(
                output,
                "callback_{}: {},",
                types::rust_identifier(&callback.name),
                self.callback_type(callback)?
            )
            .unwrap();
            let _ = lowered;
        }
        for (slot, lowered) in source.slots.iter().zip(&ir.slots) {
            writeln!(
                output,
                "slot_{}: RefCell<Vec<::argui::ui::Element>> ,",
                types::rust_identifier(&slot.name)
            )
            .unwrap();
            let _ = lowered;
        }
        writeln!(output, "}}").unwrap();
        self.emit_public_impl(output, source, ir, &name)?;
        Ok(())
    }

    /// Returns semantic component metadata for an IR ID.
    fn component_definition(&self, id: ComponentId) -> Result<&ComponentDefinition, CompilerError> {
        self.component_definitions.get(&id).copied().ok_or_else(|| {
            CompilerError::Codegen(format!("component {} has no semantic ABI", id.raw()))
        })
    }
}

/// Escapes a string for a generated Rust literal.
fn escape(value: &str) -> String {
    value.escape_default().to_string()
}
