// Generated by packages/react/scripts/generate-jsx.mjs from argui-schema.
import type { ReactNode, Ref } from 'react'
import type { AssetRef } from '@argui/host'
import type { WorkNode } from './tree'
export namespace JSX {
  export type Element = import('react').ReactElement
  export interface IntrinsicAttributes { key?: import('react').Key }
  export interface ElementChildrenAttribute { children: {} }
  export interface IntrinsicElements {
    container: {
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      min_width?: number
      min_height?: number
      background?: string
      selection_fill?: string
      selection_color?: string
      selection_radius?: number
      gap?: number
      loop_ms?: number
      loop_playing?: boolean
      loop_gap?: number
      padding?: number
      scroll_y?: boolean
      scrollbar_thumb?: string
      wrap?: boolean
      grow?: number
      shrink?: number
      border_color?: string
      radius?: number
      align_items?: string
      justify_content?: string
      grid_rows?: string
      grid_columns?: string
      grid_row_start?: number
      grid_row_span?: number
      grid_column_start?: number
      grid_column_span?: number
      max_width?: number
      max_height?: number
      aspect_ratio?: number
      flex_basis?: number | string
      row_gap?: number
      column_gap?: number
      padding_left?: number
      padding_right?: number
      padding_top?: number
      padding_bottom?: number
      margin_left?: number
      margin_right?: number
      margin_top?: number
      margin_bottom?: number
      scale_x?: number
      scale_y?: number
      translate_x?: number
      translate_y?: number
      origin_x?: number
      origin_y?: number
      position?: string
      inset_left?: number
      inset_right?: number
      inset_top?: number
      inset_bottom?: number
      z_index?: number
      query_scope?: string
      query_min_width?: number
      query_columns?: string
      align_self?: string
      justify_items?: string
      justify_self?: string
      align_content?: string
      grid_auto_flow?: string
      radius_top_left?: number
      radius_top_right?: number
      radius_bottom_right?: number
      radius_bottom_left?: number
      border_left?: number
      border_right?: number
      border_top?: number
      border_bottom?: number
      shadow_offset_x?: number
      shadow_spread?: number
      clip?: boolean
      shadow_blur?: number
      shadow_offset_y?: number
      shadow_color?: string
      transition_ms?: number
      transition_spring?: boolean
      onClick?: (payload: unknown) => void
      onFocus?: (payload: unknown) => void
      onBlur?: (payload: unknown) => void
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    row: {
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      min_width?: number
      min_height?: number
      background?: string
      selection_fill?: string
      selection_color?: string
      selection_radius?: number
      gap?: number
      loop_ms?: number
      loop_playing?: boolean
      loop_gap?: number
      padding?: number
      scroll_y?: boolean
      scrollbar_thumb?: string
      wrap?: boolean
      grow?: number
      shrink?: number
      border_color?: string
      radius?: number
      align_items?: string
      justify_content?: string
      grid_rows?: string
      grid_columns?: string
      grid_row_start?: number
      grid_row_span?: number
      grid_column_start?: number
      grid_column_span?: number
      max_width?: number
      max_height?: number
      aspect_ratio?: number
      flex_basis?: number | string
      row_gap?: number
      column_gap?: number
      padding_left?: number
      padding_right?: number
      padding_top?: number
      padding_bottom?: number
      margin_left?: number
      margin_right?: number
      margin_top?: number
      margin_bottom?: number
      scale_x?: number
      scale_y?: number
      translate_x?: number
      translate_y?: number
      origin_x?: number
      origin_y?: number
      position?: string
      inset_left?: number
      inset_right?: number
      inset_top?: number
      inset_bottom?: number
      z_index?: number
      query_scope?: string
      query_min_width?: number
      query_columns?: string
      align_self?: string
      justify_items?: string
      justify_self?: string
      align_content?: string
      grid_auto_flow?: string
      radius_top_left?: number
      radius_top_right?: number
      radius_bottom_right?: number
      radius_bottom_left?: number
      border_left?: number
      border_right?: number
      border_top?: number
      border_bottom?: number
      shadow_offset_x?: number
      shadow_spread?: number
      clip?: boolean
      shadow_blur?: number
      shadow_offset_y?: number
      shadow_color?: string
      transition_ms?: number
      transition_spring?: boolean
      onClick?: (payload: unknown) => void
      onFocus?: (payload: unknown) => void
      onBlur?: (payload: unknown) => void
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    column: {
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      min_width?: number
      min_height?: number
      background?: string
      selection_fill?: string
      selection_color?: string
      selection_radius?: number
      gap?: number
      loop_ms?: number
      loop_playing?: boolean
      loop_gap?: number
      padding?: number
      scroll_y?: boolean
      scrollbar_thumb?: string
      wrap?: boolean
      grow?: number
      shrink?: number
      border_color?: string
      radius?: number
      align_items?: string
      justify_content?: string
      grid_rows?: string
      grid_columns?: string
      grid_row_start?: number
      grid_row_span?: number
      grid_column_start?: number
      grid_column_span?: number
      max_width?: number
      max_height?: number
      aspect_ratio?: number
      flex_basis?: number | string
      row_gap?: number
      column_gap?: number
      padding_left?: number
      padding_right?: number
      padding_top?: number
      padding_bottom?: number
      margin_left?: number
      margin_right?: number
      margin_top?: number
      margin_bottom?: number
      scale_x?: number
      scale_y?: number
      translate_x?: number
      translate_y?: number
      origin_x?: number
      origin_y?: number
      position?: string
      inset_left?: number
      inset_right?: number
      inset_top?: number
      inset_bottom?: number
      z_index?: number
      query_scope?: string
      query_min_width?: number
      query_columns?: string
      align_self?: string
      justify_items?: string
      justify_self?: string
      align_content?: string
      grid_auto_flow?: string
      radius_top_left?: number
      radius_top_right?: number
      radius_bottom_right?: number
      radius_bottom_left?: number
      border_left?: number
      border_right?: number
      border_top?: number
      border_bottom?: number
      shadow_offset_x?: number
      shadow_spread?: number
      clip?: boolean
      shadow_blur?: number
      shadow_offset_y?: number
      shadow_color?: string
      transition_ms?: number
      transition_spring?: boolean
      onClick?: (payload: unknown) => void
      onFocus?: (payload: unknown) => void
      onBlur?: (payload: unknown) => void
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    text: {
      content?: string
      text?: string
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      background?: string
      loop_ms?: number
      loop_playing?: boolean
      loop_opacity?: number
      transition_ms?: number
      transition_spring?: boolean
      selection_fill?: string
      selection_color?: string
      selection_radius?: number
      color?: string
      weight?: number
      font_size?: number
      no_wrap?: boolean
      line_height?: number
      font_style?: string
      letter_spacing?: number
      underline?: string
      strikethrough?: boolean
      text_align?: string
      line_clamp?: number
      text_overflow?: string
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    image: {
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      source: AssetRef
      fit?: string
      sampling?: string
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    svg: {
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      source: AssetRef
      fit?: string
      color?: string
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    rectangle: {
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      min_width?: number
      min_height?: number
      rotation?: number
      rotation_loop_ms?: number
      loop_ms?: number
      loop_playing?: boolean
      loop_translate_x?: number
      loop_translate_y?: number
      loop_scale?: number
      loop_opacity?: number
      loop_background?: string
      loop_hold?: boolean
      loop_width?: number
      loop_radius?: number
      opacity?: number
      transition_ms?: number
      transition_spring?: boolean
      backdrop_filter?: string
      visible?: boolean
      background?: string
      border_color?: string
      border_width?: number
      radius?: number
      clip?: boolean
      shadow_blur?: number
      shadow_offset_y?: number
      shadow_color?: string
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    touchArea: {
      nativeKey?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      enabled?: boolean
      mouse_cursor?: string
      onClick?: (payload: unknown) => void
      onContextMenu?: (payload: unknown) => void
      onDoubleClicked?: (payload: unknown) => void
      onPointerEnter?: (payload: unknown) => void
      onPointerLeave?: (payload: unknown) => void
      onPointerDown?: (payload: unknown) => void
      onPointerUp?: (payload: unknown) => void
      onPointerMove?: (payload: unknown) => void
      onPointerCancel?: (payload: unknown) => void
      onMoved?: (payload: unknown) => void
      onDragX?: (payload: unknown) => void
      onDragY?: (payload: unknown) => void
      onWheel?: (payload: unknown) => void
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    focusScope: {
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      enabled?: boolean
      focus_on_click?: boolean
      focus_on_tab_navigation?: boolean
      containment?: string
      restore_focus?: boolean
      initial_focus?: string
      keyboard_activation?: string
      role?: string
      accessible_name?: string
      accessible_description?: string
      accessible_value?: string
      selected?: boolean
      current?: string
      controls?: string
      active_descendant?: string
      labelled_by?: string
      described_by?: string
      invalid?: boolean
      live?: string
      busy?: boolean
      checked?: boolean
      expandable?: boolean
      expanded?: boolean
      onClick?: (payload: unknown) => void
      onFocus?: (payload: unknown) => void
      onBlur?: (payload: unknown) => void
      onKey?: (payload: unknown) => void
      onCaptureKey?: (payload: unknown) => void
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    path: {
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      source: AssetRef
      fit?: string
      color?: string
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    textInput: {
      nativeKey?: string
      value?: string
      placeholder?: string
      enabled?: boolean
      read_only?: boolean
      search?: boolean
      multiline?: boolean
      max_digits?: number
      label?: string
      description?: string
      invalid?: boolean
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      background?: string
      selection_fill?: string
      selection_radius?: number
      text_color?: string
      placeholder_color?: string
      selection_color?: string
      caret_color?: string
      caret_fill?: string
      caret_width?: number
      caret_height?: number
      caret_radius?: number
      caret_count?: number
      caret_spacing?: number
      caret_offset_y?: number
      caret_blink?: boolean
      onInput?: (payload: unknown) => void
      onEdit?: (payload: unknown) => void
      onSubmit?: (payload: unknown) => void
      onFocus?: (payload: unknown) => void
      onBlur?: (payload: unknown) => void
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    keyBinding: {
      nativeKey?: string
      opacity?: number
      visible?: boolean
      shortcut: string
      enabled?: boolean
      onActivated?: (payload: unknown) => void
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    popupWindow: {
      nativeKey?: string
      width?: number | string
      height?: number | string
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      anchor?: string
      placement?: string
      dismiss_policy?: string
      window_layer?: string
      containment?: string
      restore_focus?: boolean
      initial_focus?: string
      onDismiss?: (payload: unknown) => void
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    flickable: {
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      min_width?: number
      min_height?: number
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      enabled?: boolean
      scroll_x?: boolean
      scroll_y?: boolean
      grow?: number
      onScroll?: (payload: unknown) => void
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    virtualWindow: {
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      min_width?: number
      min_height?: number
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      grow?: number
      row_height: number
      variable_height?: boolean
      viewport_height?: number
      offset?: number
      scrollbar_thumb?: string
      overscan?: number
      __item_count?: number
      __window_start?: number
      onScroll?: (payload: unknown) => void
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
    grid: {
      nativeKey?: string
      tooltip?: string
      width?: number | string
      height?: number | string
      x?: number | string
      y?: number | string
      rotation?: number
      opacity?: number
      backdrop_filter?: string
      visible?: boolean
      min_width?: number
      min_height?: number
      background?: string
      selection_fill?: string
      selection_color?: string
      selection_radius?: number
      gap?: number
      loop_ms?: number
      loop_playing?: boolean
      loop_gap?: number
      padding?: number
      scroll_y?: boolean
      scrollbar_thumb?: string
      wrap?: boolean
      grow?: number
      shrink?: number
      border_color?: string
      radius?: number
      align_items?: string
      justify_content?: string
      grid_rows?: string
      grid_columns?: string
      grid_row_start?: number
      grid_row_span?: number
      grid_column_start?: number
      grid_column_span?: number
      max_width?: number
      max_height?: number
      aspect_ratio?: number
      flex_basis?: number | string
      row_gap?: number
      column_gap?: number
      padding_left?: number
      padding_right?: number
      padding_top?: number
      padding_bottom?: number
      margin_left?: number
      margin_right?: number
      margin_top?: number
      margin_bottom?: number
      scale_x?: number
      scale_y?: number
      translate_x?: number
      translate_y?: number
      origin_x?: number
      origin_y?: number
      position?: string
      inset_left?: number
      inset_right?: number
      inset_top?: number
      inset_bottom?: number
      z_index?: number
      query_scope?: string
      query_min_width?: number
      query_columns?: string
      align_self?: string
      justify_items?: string
      justify_self?: string
      align_content?: string
      grid_auto_flow?: string
      radius_top_left?: number
      radius_top_right?: number
      radius_bottom_right?: number
      radius_bottom_left?: number
      border_left?: number
      border_right?: number
      border_top?: number
      border_bottom?: number
      shadow_offset_x?: number
      shadow_spread?: number
      clip?: boolean
      shadow_blur?: number
      shadow_offset_y?: number
      shadow_color?: string
      transition_ms?: number
      transition_spring?: boolean
      onClick?: (payload: unknown) => void
      onFocus?: (payload: unknown) => void
      onBlur?: (payload: unknown) => void
      key?: import('react').Key
      ref?: Ref<WorkNode>
      children?: ReactNode
    }
  }
}
