[package]
name = "argui-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Retained interface elements, styles and events for Argui"

[dependencies]
argui-accessibility.workspace = true
argui-animation.workspace = true
argui-core.workspace = true
argui-paint.workspace = true
argui-text.workspace = true
taffy.workspace = true
unicode-segmentation.workspace = true
web-time.workspace = true

[lints]
workspace = true
