[package]
name = "argui-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
argui-accessibility.workspace = true
argui-animation.workspace = true
argui-core.workspace = true
argui-paint.workspace = true
argui-text.workspace = true
taffy.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
argui-widgets.workspace = true

[lints]
workspace = true
