use std::ops::Range;

use argui_paint::{
    DisplayCommand, DisplayList, DisplayListError, EffectInstance, Filter, LayerStyle,
};

use crate::batch::{DrawBatch, DrawKind};
use crate::{effect_plan::plan_filters, target::PixelRegion};

#[derive(Clone, Debug, PartialEq)]
pub(crate) enum EffectNode {
    Draw(DrawBatch),
    Layer(Box<EffectLayer>),
}

#[derive(Clone, Debug, PartialEq)]
pub(crate) struct EffectLayer {
    pub style: LayerStyle,
    pub children: Vec<EffectNode>,
    pub region: Option<PixelRegion>,
    pub content_revision: u64,
    pub command_range: Range<usize>,
}

impl EffectLayer {
    /// Returns whether any child samples the scene behind this layer.
    ///
    /// A backdrop-reading child makes the parent foreground depend on pixels
    /// outside its own content and therefore unsuitable for the layer cache.
    #[must_use]
    pub(crate) fn content_reads_backdrop(&self) -> bool {
        self.children.iter().any(|node| match node {
            EffectNode::Draw(_) => false,
            EffectNode::Layer(child) => {
                !child.style.backdrop_filters.is_empty() || child.content_reads_backdrop()
            }
        })
    }
}

#[derive(Clone, Debug, Default)]
pub(crate) struct EffectGraph {
    pub roots: Vec<EffectNode>,
}

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct EffectGraphStats {
    pub layers: usize,
    pub offscreen_layers: usize,
    pub draw_batches: usize,
    pub filter_passes: usize,
    pub offscreen_pixels: u64,
    pub cached_layers: usize,
    pub damaged_pixels: u64,
}

/// Renderer-neutral analysis of the passes generated by one display list.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct EffectGraphAnalysis {
    pub stats: EffectGraphStats,
    pub custom_effects: Vec<argui_paint::EffectId>,
}

/// Validates and analyzes a display list without creating GPU resources.
///
/// # Arguments
/// * `display_list` — commands to validate and analyze.
/// * `text_ranges` — prepared text ranges referenced by text commands.
/// * `viewport` — target dimensions in physical pixels.
/// * `scale_factor` — logical-to-physical scale.
/// * `content_revision` — revision key used for retained content.
///
/// # Errors
/// Returns an error if the display list contains invalid commands or references.
pub fn analyze_display_list(
    display_list: &DisplayList,
    text_ranges: &[Range<u32>],
    viewport: [f32; 2],
    scale_factor: f32,
    content_revision: u64,
) -> Result<EffectGraphAnalysis, DisplayListError> {
    let graph = EffectGraph::build(
        display_list,
        text_ranges,
        viewport,
        scale_factor,
        content_revision,
    )?;
    Ok(EffectGraphAnalysis {
        stats: graph.stats(),
        custom_effects: graph
            .effects()
            .into_iter()
            .map(|effect| effect.id.clone())
            .collect(),
    })
}

impl EffectGraph {
    pub fn build(
        display_list: &DisplayList,
        text_ranges: &[Range<u32>],
        viewport: [f32; 2],
        scale_factor: f32,
        content_revision: u64,
    ) -> Result<Self, DisplayListError> {
        display_list.validate()?;
        let mut roots = Vec::new();
        let mut stack: Vec<EffectLayer> = Vec::new();
        let mut quad = 0_u32;
        let mut image = 0_u32;
        let mut vector = 0_u32;
        let mut gpu_canvas = 0_u32;
        for (command_index, command) in display_list.commands().iter().enumerate() {
            match command {
                DisplayCommand::Quad(_) => {
                    push_draw(&mut roots, &mut stack, DrawKind::Quad, quad..quad + 1);
                    quad += 1;
                }
                DisplayCommand::Text { block, .. } => push_draw(
                    &mut roots,
                    &mut stack,
                    DrawKind::Text,
                    text_ranges.get(*block).cloned().unwrap_or(0..0),
                ),
                DisplayCommand::Image(item) => {
                    push_draw(
                        &mut roots,
                        &mut stack,
                        DrawKind::Image(item.image, item.sampling),
                        image..image + 1,
                    );
                    image += 1;
                }
                DisplayCommand::GpuCanvas(_) => {
                    push_draw(
                        &mut roots,
                        &mut stack,
                        DrawKind::GpuCanvas(gpu_canvas),
                        gpu_canvas..gpu_canvas + 1,
                    );
                    gpu_canvas += 1;
                }
                DisplayCommand::Vector(_) => {
                    push_draw(&mut roots, &mut stack, DrawKind::Vector, vector..vector + 1);
                    vector += 1;
                }
                DisplayCommand::BeginLayer(style) => {
                    let style = style.scaled(scale_factor);
                    let viewport = PixelRegion::viewport(viewport[0] as u32, viewport[1] as u32);
                    let region = match stack.last() {
                        Some(parent) => parent.region.and_then(|parent| {
                            PixelRegion::from_rect(style.expanded_bounds(), parent)
                        }),
                        None => PixelRegion::from_rect(style.expanded_bounds(), viewport),
                    };
                    stack.push(EffectLayer {
                        region,
                        style,
                        children: Vec::new(),
                        content_revision,
                        command_range: command_index..command_index + 1,
                    });
                }
                DisplayCommand::BeginCompositor(layer) => {
                    let style = layer.style().scaled(scale_factor);
                    let viewport = PixelRegion::viewport(viewport[0] as u32, viewport[1] as u32);
                    let region = match stack.last() {
                        Some(parent) => parent.region.and_then(|parent| {
                            PixelRegion::from_rect(style.expanded_bounds(), parent)
                        }),
                        None => PixelRegion::from_rect(style.expanded_bounds(), viewport),
                    };
                    stack.push(EffectLayer {
                        region,
                        style,
                        children: Vec::new(),
                        content_revision,
                        command_range: command_index..command_index + 1,
                    });
                }
                DisplayCommand::EndLayer | DisplayCommand::EndCompositor => {
                    let mut layer = stack.pop().expect("validated layer stack");
                    layer.command_range.end = command_index + 1;
                    push_node(&mut roots, &mut stack, EffectNode::Layer(Box::new(layer)));
                }
            }
        }
        Ok(Self { roots })
    }

    /// Retains cached revisions for layers whose display commands did not change.
    ///
    /// * `previous`, `current` — adjacent scene snapshots.
    /// * `force_refresh` — whether GPU content changed without a matching
    ///   command change, requiring every layer to keep the new revision.
    /// * `cached_revision` — returns a previously rendered layer's revision
    ///   for its profile identity, or `None` when it has no cached content.
    pub(crate) fn retain_layer_revisions(
        &mut self,
        previous: Option<&crate::DamageSnapshot>,
        current: &crate::DamageSnapshot,
        force_refresh: bool,
        cached_revision: &impl Fn(argui_paint::RenderObjectId) -> Option<u64>,
    ) {
        /// Recursively preserves the revision of each visually unchanged layer.
        ///
        /// `nodes` is the graph subtree; `previous` and `current` are adjacent
        /// snapshots. `force_refresh` denies reuse after untracked GPU changes.
        /// `cached_revision` looks up a prior revision by profile identity.
        fn visit(
            nodes: &mut [EffectNode],
            previous: Option<&crate::DamageSnapshot>,
            current: &crate::DamageSnapshot,
            force_refresh: bool,
            cached_revision: &impl Fn(argui_paint::RenderObjectId) -> Option<u64>,
        ) {
            for node in nodes {
                if let EffectNode::Layer(layer) = node {
                    if !force_refresh
                        && previous.is_some_and(|previous| {
                            previous.unchanged_range(current, layer.command_range.clone())
                        })
                        && let Some(revision) = layer.style.profile.and_then(cached_revision)
                    {
                        layer.content_revision = revision;
                    }
                    visit(
                        &mut layer.children,
                        previous,
                        current,
                        force_refresh,
                        cached_revision,
                    );
                }
            }
        }
        visit(
            &mut self.roots,
            previous,
            current,
            force_refresh,
            cached_revision,
        );
    }

    #[must_use]
    pub fn stats(&self) -> EffectGraphStats {
        fn visit(nodes: &[EffectNode], stats: &mut EffectGraphStats) {
            for node in nodes {
                match node {
                    EffectNode::Draw(_) => stats.draw_batches += 1,
                    EffectNode::Layer(layer) if layer.style.opacity <= 0.0 => {}
                    EffectNode::Layer(layer) => {
                        stats.layers += 1;
                        stats.offscreen_layers += usize::from(layer.style.requires_offscreen());
                        stats.filter_passes += plan_filters(&layer.style.filters).len()
                            + plan_filters(&layer.style.backdrop_filters).len()
                            + layer.style.shadows.len() * 2;
                        if layer.style.requires_offscreen()
                            && let Some(region) = layer.region
                        {
                            stats.offscreen_pixels +=
                                u64::from(region.size[0]) * u64::from(region.size[1]);
                        }
                        visit(&layer.children, stats);
                    }
                }
            }
        }
        let mut stats = EffectGraphStats::default();
        visit(&self.roots, &mut stats);
        stats
    }

    #[must_use]
    pub fn needs_offscreen_root(&self) -> bool {
        /// Returns whether this node slice contains an offscreen layer.
        fn visit(nodes: &[EffectNode]) -> bool {
            nodes.iter().any(|node| match node {
                EffectNode::Draw(_) => false,
                EffectNode::Layer(layer) => {
                    layer.style.requires_offscreen() || visit(&layer.children)
                }
            })
        }
        visit(&self.roots)
    }

    pub fn effects(&self) -> Vec<&EffectInstance> {
        fn visit<'a>(nodes: &'a [EffectNode], effects: &mut Vec<&'a EffectInstance>) {
            for node in nodes {
                if let EffectNode::Layer(layer) = node
                    && layer.style.opacity > 0.0
                {
                    for filter in layer
                        .style
                        .filters
                        .iter()
                        .chain(&layer.style.backdrop_filters)
                    {
                        if let Filter::Effect(effect) = filter {
                            effects.push(effect);
                        }
                    }
                    visit(&layer.children, effects);
                }
            }
        }
        let mut effects = Vec::new();
        visit(&self.roots, &mut effects);
        effects
    }

    /// Returns every stable profile identifier present in active graph layers.
    #[must_use]
    pub(crate) fn profiles(&self) -> std::collections::HashSet<argui_paint::RenderObjectId> {
        fn visit(
            nodes: &[EffectNode],
            profiles: &mut std::collections::HashSet<argui_paint::RenderObjectId>,
        ) {
            for node in nodes {
                if let EffectNode::Layer(layer) = node
                    && layer.style.opacity > 0.0
                {
                    if let Some(profile) = layer.style.profile {
                        profiles.insert(profile);
                    }
                    visit(&layer.children, profiles);
                }
            }
        }
        let mut profiles = std::collections::HashSet::new();
        visit(&self.roots, &mut profiles);
        profiles
    }
}

fn push_draw(
    roots: &mut Vec<EffectNode>,
    stack: &mut [EffectLayer],
    kind: DrawKind,
    instances: Range<u32>,
) {
    if instances.is_empty() {
        return;
    }
    let nodes = stack.last_mut().map_or(roots, |layer| &mut layer.children);
    if let Some(EffectNode::Draw(previous)) = nodes.last_mut()
        && previous.kind == kind
        && previous.instances.end == instances.start
    {
        previous.instances.end = instances.end;
    } else {
        nodes.push(EffectNode::Draw(DrawBatch { kind, instances }));
    }
}

fn push_node(roots: &mut Vec<EffectNode>, stack: &mut [EffectLayer], node: EffectNode) {
    stack
        .last_mut()
        .map_or(roots, |layer| &mut layer.children)
        .push(node);
}
