[package]
name = "argui-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
tray = ["argui-platform/tray"]

[dependencies]
argui-inspect.workspace = true
argui-animation.workspace = true
argui-core.workspace = true
argui-layout.workspace = true
argui-paint.workspace = true
argui-platform.workspace = true
argui-render.workspace = true
argui-text.workspace = true
argui-ui.workspace = true
winit.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures.workspace = true

[lints]
workspace = true
