[package]
name = "argui-dsl-stdlib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Embedded source modules for the official Argui DSL component library"

[features]
default = ["icons"]
icons = ["dep:icondata_core", "dep:icondata_tb"]

[dependencies]
icondata_core = { workspace = true, optional = true }
icondata_tb = { workspace = true, optional = true }

[lints]
workspace = true
