[package]
name = "argui-widgets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
all = ["file-picker", "label", "skeleton", "breadcrumb", "pagination", "avatar", "empty", "kbd", "aspect-ratio", "progress", "badge", "card", "alert", "separator", "collapsible", "data-table", "toast", "date-picker", "calendar", "button", "input", "checkbox", "switch", "radio-group", "tabs", "select", "popover", "dialog", "range", "slider", "spinner", "text-selection", "split-pane", "vlist", "list", "table", "tree-view", "icons", "menu", "context-menu", "menubar", "command-palette", "textarea", "tooltip"]
file-picker = ["button", "dep:argui-platform", "argui-platform/file-picker", "dep:argui-runtime", "argui-runtime/tasks"]
label = []
skeleton = ["dep:argui-runtime"]
breadcrumb = ["button"]
pagination = ["button"]
avatar = []
empty = []
kbd = []
aspect-ratio = []
progress = ["dep:argui-runtime"]
badge = []
card = []
alert = []
separator = []
collapsible = ["button"]
data-table = ["table", "input", "checkbox", "button", "split-pane", "icons"]
toast = ["button", "icons"]
date-picker = ["calendar", "input", "popover"]
calendar = ["button", "dep:time"]
menu = ["button", "popover", "icons"]
context-menu = ["menu"]
menubar = ["menu"]
command-palette = ["menu", "input"]
button = []
input = []
textarea = []
checkbox = []
switch = []
radio-group = []
tabs = []
select = ["input"]
popover = []
tooltip = ["dep:argui-runtime", "argui-runtime/tasks", "dep:argui-inspect", "dep:web-time"]
dialog = []
range = ["dep:argui-runtime"]
slider = ["range"]
spinner = ["dep:argui-runtime"]
text-selection = ["button", "icons", "dep:argui-runtime", "dep:argui-inspect"]
split-pane = []
list = []
table = ["list"]
vlist = ["list"]
tree-view = ["vlist", "button"]
icons = ["dep:argui-vector", "dep:icondata_core", "dep:icondata_tb"]

[dependencies]
argui-platform = { workspace = true, optional = true }
web-time = { workspace = true, optional = true }
time = { version = "=0.3.44", optional = true, features = ["parsing"] }
argui-animation.workspace = true
argui-core.workspace = true
argui-inspect = { workspace = true, optional = true }
argui-paint.workspace = true
argui-runtime = { workspace = true, optional = true }
argui-text.workspace = true
argui-theme.workspace = true
argui-ui.workspace = true
argui-vector = { workspace = true, optional = true }
icondata_core = { workspace = true, optional = true }
icondata_tb = { workspace = true, optional = true }

[dev-dependencies]
argui-layout.workspace = true

[lints]
workspace = true
