import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '../../..')
const contract = JSON.parse(execFileSync('cargo', [
  'run', '--quiet', '--offline', '--all-features', '-p', 'argui-schema', '--example', 'export_contract',
], { cwd: root, encoding: 'utf8' }))
const valueType = {
  Bool: 'boolean', Int: 'number', Float: 'number', String: 'string', Name: 'string',
  Color: 'string', Brush: 'string', Dimension: 'number | string',
  Insets: 'number | readonly number[]', Radii: 'number | readonly number[]',
  Border: 'object', Shadow: 'object', Transform: 'object', Asset: 'AssetRef',
}
const semanticType = {
  role: 'SemanticRole', current: 'SemanticCurrent', live: 'SemanticLive',
  checked_state: 'SemanticCheckedState', keyboard_activation: 'KeyboardActivation',
  orientation: 'SemanticOrientation', has_popup: 'SemanticPopup', sort: 'SemanticSort',
}
const lines = [
  '// Generated by packages/solid/scripts/generate-jsx.mjs from argui-schema.',
  "import type { AssetRef, NativeNode, SemanticRole, SemanticCurrent, SemanticLive, SemanticCheckedState, SemanticOrientation, SemanticPopup, SemanticSort, KeyboardActivation, SemanticActionPayload } from '@argui/host'",
  'export namespace JSX {',
  "  export type Element = import('solid-js').JSX.Element | NativeNode | readonly Element[]",
  '  export interface ElementChildrenAttribute { children: {} }',
  '  export interface IntrinsicElements {',
]
for (const native of contract.natives) {
  const tag = native.name[0].toLowerCase() + native.name.slice(1)
  lines.push(`    ${tag}: {`)
  for (const property of native.properties) {
    if (property.readOnly) continue
    lines.push(`      ${property.name}${property.required ? ':' : '?:'} ${semanticType[property.name] ?? valueType[property.valueType] ?? 'unknown'}`)
  }
  for (const event of native.events) {
    const name = 'on' + event.name.replace(/(^|_)([a-z])/g, (_, _separator, letter) => letter.toUpperCase())
    lines.push(`      ${name}?: (payload: ${event.name === 'semantic_action' ? 'SemanticActionPayload' : 'unknown'}) => void`)
  }
  lines.push('      ref?: (node: NativeNode) => void')
  lines.push('      children?: Element | readonly Element[]')
  lines.push('    }')
}
lines.push('  }', '}', '')
writeFileSync(resolve(root, 'packages/solid/src/jsx.generated.ts'), lines.join('\n'))
writeFileSync(resolve(root, 'packages/host/src/contract.generated.json'), JSON.stringify(contract, null, 2) + '\n')
