// Generated by scripts/generate-app-assets.mjs.
import type { AssetRef } from '@argui/host'
declare const __ARGUI_DEV_ASSETS__: boolean
const developmentAssets = {
  "gallery/button.svg": { kind: "svg", id: 210289702017226 },
  "gallery/layout-example.svg": { kind: "svg", id: 7074010601567763 },
  "gallery/moon.svg": { kind: "svg", id: 8534080480914967 },
  "gallery/popover.svg": { kind: "svg", id: 8075436257117667 },
  "gallery/select.svg": { kind: "svg", id: 3150152941818794 },
  "gallery/settings.svg": { kind: "svg", id: 4003285612405311 },
  "gallery/sun.svg": { kind: "svg", id: 2429037204418036 },
  "gallery/system.svg": { kind: "svg", id: 5782066887110427 },
  "gallery/text-input.svg": { kind: "svg", id: 3008935926873864 },
  "gallery/virtual-list.svg": { kind: "svg", id: 3659538044321220 },
  "illustration/orbit.png": { kind: "image", id: 2571842761405680 },
  "illustration/orbit.svg": { kind: "svg", id: 6003398377895504 },
  "photo/saturn.jpg": { kind: "image", id: 182680722277923 },
  "tabler/check.svg": { kind: "svg", id: 4418227052333180 },
  "tabler/chevron-down.svg": { kind: "svg", id: 5981616865338806 },
  "tabler/chevron-right.svg": { kind: "svg", id: 8016896629891356 },
  "tabler/heart.svg": { kind: "svg", id: 4333451266351680 },
  "tabler/loader-2.svg": { kind: "svg", id: 5035487383804796 },
  "tabler/photo.svg": { kind: "svg", id: 1456439125952080 },
  "tabler/player-play.svg": { kind: "svg", id: 6833585511893982 },
  "tabler/search.svg": { kind: "svg", id: 2000023927804256 },
  "tabler/star-filled.svg": { kind: "svg", id: 6122411386721923 },
  "tabler/star.svg": { kind: "svg", id: 1326099470823436 },
  "tabler/x.svg": { kind: "svg", id: 8953272632637284 },
} as const satisfies Record<string, AssetRef>
const releaseAssets = {
  "gallery/moon.svg": { kind: "svg", id: 8534080480914967 },
  "gallery/settings.svg": { kind: "svg", id: 4003285612405311 },
  "gallery/sun.svg": { kind: "svg", id: 2429037204418036 },
  "gallery/system.svg": { kind: "svg", id: 5782066887110427 },
  "tabler/chevron-down.svg": { kind: "svg", id: 5981616865338806 },
  "tabler/search.svg": { kind: "svg", id: 2000023927804256 },
  "tabler/star.svg": { kind: "svg", id: 1326099470823436 },
} as const satisfies Record<string, AssetRef>
/** Application-owned references; development can expose the configured packs. */
export const mediaAssets: Record<string, AssetRef> = typeof __ARGUI_DEV_ASSETS__ !== 'undefined' && __ARGUI_DEV_ASSETS__ ? developmentAssets : releaseAssets
