[package]
name = "argui-widget-gallery"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
updater = ["argui/widget-updater", "dep:argui-updater"]
all-smi = ["argui-devtools/all-smi"]
desktop-backdrop = ["argui/desktop-backdrop"]
native-popups = ["argui/native-popups"]
webview = ["argui/webview"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
web-time.workspace = true
argui = { workspace = true, features = ["widgets-all", "tasks"] }
argui-image.workspace = true
argui-updater = { workspace = true, optional = true }
argui-effects = { workspace = true, features = ["artistic", "blur", "shadow", "scroll", "liquid-glass"] }
argui-devtools.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen.workspace = true

[lints]
workspace = true
