[package]
name = "argui-devtools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
all-smi = []

[dependencies]
argui-animation.workspace = true
argui-effects = { workspace = true, features = ["scroll"] }
argui-core.workspace = true
argui-inspect.workspace = true
argui-paint.workspace = true
argui-platform.workspace = true
argui-render.workspace = true
argui-runtime.workspace = true
argui-text.workspace = true
argui-theme.workspace = true
argui-ui.workspace = true
argui-vector.workspace = true
argui-widgets = { workspace = true, features = ["button", "input", "checkbox", "tabs", "select", "split-pane", "vlist", "tree-view", "color-picker", "slider", "collapsible"] }
icondata_core.workspace = true
icondata_tb.workspace = true
serde_json.workspace = true
web-time.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sysinfo = { workspace = true, features = ["system"] }

[dev-dependencies]
argui-layout.workspace = true
argui-showcase.workspace = true

[lints]
workspace = true
