[package]
name = "argui-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
tray = ["dep:ksni", "dep:tray-icon"]

[dependencies]
argui-core.workspace = true
image.workspace = true
winit.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
arboard.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
ashpd.workspace = true
ksni = { workspace = true, optional = true }
pollster.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = ["UI_ViewManagement"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit.workspace = true

[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
tray-icon = { workspace = true, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
base64.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = ["Clipboard", "Document", "Element", "HtmlCanvasElement", "HtmlHeadElement", "MediaQueryList", "Navigator", "Node", "NodeList", "Window"] }

[lints]
workspace = true
